import { useState, useEffect } from 'react'
import styled from 'styled-components'
import { hybridAPI } from '../services/api'
import { 
  FiActivity, FiAlertTriangle, FiCheckCircle, FiClock, 
  FiRefreshCw, FiTrendingUp 
} from 'react-icons/fi'

const DashboardContainer = styled.div`
  display: flex;
  flex-direction: column;
  gap: 2rem;
`

const TopBar = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  
  @media (max-width: 768px) {
    flex-direction: column;
    gap: 1rem;
    align-items: flex-start;
  }
`

const PageTitle = styled.div`
  h2 {
    font-size: 1.75rem;
    color: var(--text-primary);
    font-weight: 600;
    margin-bottom: 0.5rem;
  }
  
  p {
    color: var(--text-secondary);
    font-size: 0.95rem;
  }
`

const RefreshButton = styled.button`
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.5rem;
  background: var(--bg-tertiary);
  border: 1px solid var(--border-color);
  color: var(--text-primary);
  border-radius: var(--radius-md);
  cursor: pointer;
  font-weight: 500;
  transition: var(--transition);
  
  svg {
    font-size: 1.25rem;
  }
  
  &:hover {
    background: var(--primary);
    border-color: var(--primary);
    box-shadow: var(--shadow-glow);
  }
  
  &:active svg {
    animation: spin 0.5s ease;
  }
  
  @keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }
`

const StatsGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 1.5rem;
`

const StatCard = styled.div`
  background: var(--bg-card);
  border: 1px solid var(--border-color);
  border-radius: var(--radius-lg);
  padding: 1.5rem;
  transition: var(--transition);
  position: relative;
  overflow: hidden;
  
  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 3px;
    background: ${props => props.$color || 'var(--primary)'};
  }
  
  &:hover {
    transform: translateY(-4px);
    box-shadow: var(--shadow-lg);
    border-color: ${props => props.$color || 'var(--primary)'};
  }
`

const StatHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 1rem;
`

const StatIcon = styled.div`
  width: 48px;
  height: 48px;
  border-radius: var(--radius-md);
  background: ${props => props.$color ? `${props.$color}20` : 'rgba(76, 110, 245, 0.2)'};
  display: flex;
  align-items: center;
  justify-content: center;
  
  svg {
    font-size: 1.5rem;
    color: ${props => props.$color || 'var(--primary)'};
  }
`

const StatLabel = styled.div`
  font-size: 0.875rem;
  color: var(--text-secondary);
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.5px;
`

const StatValue = styled.div`
  font-size: 2rem;
  font-weight: 700;
  color: var(--text-primary);
  margin-bottom: 0.5rem;
`

const StatChange = styled.div`
  font-size: 0.875rem;
  color: ${props => props.$positive ? 'var(--success)' : 'var(--danger)'};
  display: flex;
  align-items: center;
  gap: 0.25rem;
  
  svg {
    font-size: 1rem;
  }
`

const ChartCard = styled.div`
  background: var(--bg-card);
  border: 1px solid var(--border-color);
  border-radius: var(--radius-lg);
  padding: 1.5rem;
  margin-top: 2rem;
  
  h3 {
    font-size: 1.125rem;
    color: var(--text-primary);
    font-weight: 600;
    margin-bottom: 1.5rem;
    display: flex;
    align-items: center;
    gap: 0.5rem;
    
    svg {
      color: var(--primary);
    }
  }
`

const Dashboard = () => {
  const [analytics, setAnalytics] = useState({
    totalTransactions: 0,
    lowRisk: 0,
    mediumRisk: 0,
    highRisk: 0,
    approvedCount: 0,
    holdCount: 0,
    blockedCount: 0,
    autoGeneratedCount: 0
  })

  const fetchAnalytics = async () => {
    try {
      const response = await hybridAPI.getAnalytics()
      setAnalytics(response.data)
    } catch (error) {
      console.error('Error fetching analytics:', error)
    }
  }

  useEffect(() => {
    fetchAnalytics()
    const interval = setInterval(fetchAnalytics, 2000)
    return () => clearInterval(interval)
  }, [])

  return (
    <DashboardContainer>
      <TopBar>
        <PageTitle>
          <h2>Real-Time Transaction Monitoring</h2>
          <p>Monitor fraud detection in real-time with ML + Rule-based analysis</p>
        </PageTitle>
        <RefreshButton onClick={fetchAnalytics}>
          <FiRefreshCw />
          Refresh
        </RefreshButton>
      </TopBar>

      <StatsGrid>
        <StatCard $color="var(--primary)">
          <StatHeader>
            <StatLabel>Total Transactions</StatLabel>
            <StatIcon $color="var(--primary)">
              <FiActivity />
            </StatIcon>
          </StatHeader>
          <StatValue>{analytics.totalTransactions}</StatValue>
          <StatChange $positive>
            <FiTrendingUp />
            Live monitoring active
          </StatChange>
        </StatCard>

        <StatCard $color="var(--success)">
          <StatHeader>
            <StatLabel>Low Risk</StatLabel>
            <StatIcon $color="var(--success)">
              <FiCheckCircle />
            </StatIcon>
          </StatHeader>
          <StatValue>{analytics.lowRisk}</StatValue>
          <StatChange $positive>
            Approved: {analytics.approvedCount}
          </StatChange>
        </StatCard>

        <StatCard $color="var(--warning)">
          <StatHeader>
            <StatLabel>Medium Risk</StatLabel>
            <StatIcon $color="var(--warning)">
              <FiClock />
            </StatIcon>
          </StatHeader>
          <StatValue>{analytics.mediumRisk}</StatValue>
          <StatChange>
            On Hold: {analytics.holdCount}
          </StatChange>
        </StatCard>

        <StatCard $color="var(--danger)">
          <StatHeader>
            <StatLabel>High Risk</StatLabel>
            <StatIcon $color="var(--danger)">
              <FiAlertTriangle />
            </StatIcon>
          </StatHeader>
          <StatValue>{analytics.highRisk}</StatValue>
          <StatChange $positive={false}>
            Blocked: {analytics.blockedCount}
          </StatChange>
        </StatCard>
      </StatsGrid>

      <ChartCard>
        <h3>
          <FiActivity />
          Auto-Generation Status
        </h3>
        <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem' }}>
          System automatically generates 1 transaction every 5 seconds
        </p>
        <div style={{ 
          padding: '1rem', 
          background: 'var(--bg-tertiary)', 
          borderRadius: 'var(--radius-md)',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center'
        }}>
          <span style={{ color: 'var(--text-secondary)' }}>
            Auto-generated transactions:
          </span>
          <span style={{ 
            fontSize: '1.5rem', 
            fontWeight: '700', 
            color: 'var(--primary-light)' 
          }}>
            {analytics.autoGeneratedCount}
          </span>
        </div>
        <div style={{ 
          marginTop: '1rem', 
          display: 'flex', 
          alignItems: 'center', 
          gap: '0.5rem',
          color: 'var(--success)'
        }}>
          <div style={{
            width: '8px',
            height: '8px',
            borderRadius: '50%',
            background: 'var(--success)',
            animation: 'pulse 2s ease-in-out infinite'
          }} />
          System Running
        </div>
      </ChartCard>
    </DashboardContainer>
  )
}

export default Dashboard
