package com.example.bankingsystem.hybrid;

import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@RestController
@RequestMapping("/api/hybrid")
@CrossOrigin(origins = "*")
public class HybridFraudDetectionController {

    @Autowired
    private HybridFraudDetectionService hybridService;

    @Autowired
    private TransactionGenerator transactionGenerator;

    /**
     * Manual transaction check (OLD FORMAT - for backward compatibility)
     */
    @PostMapping("/check")
    public ResponseEntity<HybridFraudDetectionResponse> checkTransaction(
            @Valid @RequestBody HybridTransactionRequest request) {
        try {
            HybridFraudDetectionResponse response = hybridService.processHybridTransaction(request);
            return ResponseEntity.ok(response);
        } catch (Exception e) {
            return ResponseEntity.badRequest().build();
        }
    }

    /**
     * REAL-TIME transaction check (NEW - calculates balances)
     * This is how real banks work - check BEFORE transaction completes
     */
    @PostMapping("/check-realtime")
    public ResponseEntity<HybridFraudDetectionResponse> checkTransactionRealTime(
            @Valid @RequestBody RealTimeTransactionRequest request) {
        try {
            // Calculate expected balances BEFORE transaction
            Double expectedSenderBalance = request.calculateExpectedSenderBalance();
            Double expectedReceiverBalance = request.calculateExpectedReceiverBalance();
            
            // Convert to old format for fraud detection
            HybridTransactionRequest fraudCheckRequest = new HybridTransactionRequest();
            fraudCheckRequest.setType(request.getType());
            fraudCheckRequest.setAmount(request.getAmount());
            fraudCheckRequest.setOldbalanceOrg(request.getSenderCurrentBalance());
            fraudCheckRequest.setNewbalanceOrig(expectedSenderBalance);
            fraudCheckRequest.setOldbalanceDest(request.getReceiverCurrentBalance());
            fraudCheckRequest.setNewbalanceDest(expectedReceiverBalance);
            fraudCheckRequest.setUserId(request.getUserId());
            fraudCheckRequest.setLocation(request.getLocation());
            fraudCheckRequest.setDevice(request.getDevice());
            fraudCheckRequest.setMerchantName(request.getMerchantName());
            fraudCheckRequest.setSenderAccountId(request.getSenderAccountId());
            fraudCheckRequest.setReceiverAccountId(request.getReceiverAccountId());
            
            // Run fraud detection
            HybridFraudDetectionResponse response = hybridService.processHybridTransaction(fraudCheckRequest);
            
            // Add decision explanation
            if (response.getStatus().equals("BLOCKED")) {
                response.setRecommendation(
                    "Transaction BLOCKED - Do NOT process payment. " + response.getRecommendation()
                );
            } else if (response.getStatus().equals("HOLD")) {
                response.setRecommendation(
                    "Transaction ON HOLD - Requires manual review before processing. " + response.getRecommendation()
                );
            } else {
                response.setRecommendation(
                    "Transaction APPROVED - Safe to process payment. " + response.getRecommendation()
                );
            }
            
            return ResponseEntity.ok(response);
        } catch (Exception e) {
            return ResponseEntity.badRequest().build();
        }
    }

    /**
     * Get analytics for dashboard
     */
    @GetMapping("/analytics")
    public ResponseEntity<Map<String, Object>> getAnalytics() {
        Map<String, Object> analytics = hybridService.getAnalytics();
        analytics.put("autoGeneratedCount", transactionGenerator.getGeneratedCount());
        return ResponseEntity.ok(analytics);
    }

    /**
     * Health check
     */
    @GetMapping("/health")
    public ResponseEntity<Map<String, String>> healthCheck() {
        return ResponseEntity.ok(Map.of(
                "status", "healthy",
                "service", "Hybrid Fraud Detection",
                "autoGeneration", "enabled"
        ));
    }
}
